main: org.example.minevidencia.essentialEmEvidencia.RepairPlugin
name: Repair
version: 1.0
author: Gabriel Prozin
api-version: 1.21.5
commands:
  repair:
    description: Repara a durabilidade dos itens
    usage: /repair [hand|all]
    aliases: [fix, efix, erepair]
